version: '3'

services:

  article-service:
    build:
      context: ./article-service
    restart: always
    environment:
      DSN: "root:somepass@tcp(mysql:3306)/main_db"
    ports:
      - "8080:8080"
  
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somepass
    volumes:
    - ./init-db:/docker-entrypoint-initdb.d
    - ./db-data/mysql:/var/lib/mysql:rw
   

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

networks:
  default:
      name: database_default